---
title: "This Guy, Elmore, Made This"
output: 
  flexdashboard::flex_dashboard:
    orientation: column
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------
### AAPL: Daily Adjusted Closing Price with 10 and 20 day SMA

```{r}
library(tidyquant)

AAPL <-
  tq_get("AAPL")
AAPL %>%
  ggplot(aes(x = date, y = adjusted)) +
  geom_line() +                         
  geom_ma(ma_fun = SMA, n = 10, color = "blue") +                 
  geom_ma(ma_fun = SMA, n = 50, color = "red") + 
  coord_x_date(xlim = c(today() - weeks(45), today()),
               ylim = c(140,195)) +
  labs(title = "AAPL: Stock Price with 10 and 20 day Moving average",
       subtitle = "Data From Yahoo Finance",
       y = "Adjusted Closing Price",
       x = "Date: 2017-2018") +
  theme_tq() +
  theme(legend.position = "left")

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### AAPL: Volume Chart

```{r}
AAPL <-
  tq_get("AAPL")
AAPL %>%
  ggplot(aes(x = date, y = volume)) +
  geom_segment(aes(xend = date, yend = 0, color = volume)) +
  geom_smooth(method = "loess", se = FALSE) +
  labs(title = "AAPL: Volume Chart",
       subtitle = "Charting Daily Volume",
       y = "Volume", x = "") +
  theme_tq() +
  theme(legend.position = "none")
```

-----------------------------------------------------------------------

### AAPL: Key Financial Ratios

```{r}
AAPLFinancial <-
  tq_get("AAPL", "key.ratios")

AAPL1 <- 
  AAPLFinancial$data[[1]]

AAPL2 <- 
  AAPLFinancial$data[[2]]

AAPL3 <-
  AAPLFinancial$data[[3]]

AAPL4 <-
  AAPLFinancial$data[[4]]

AAPL5 <-
  AAPLFinancial$data[[5]]

AAPL6 <-
  AAPLFinancial$data[[6]]

AAPL7 <-
  AAPLFinancial$data[[7]]

AAPL1 %>%
  ggplot(aes(x = date, y = value)) +
  facet_wrap(~category, ncol = 5, scales = "free") +
  geom_line() +
  labs(title = "AAPL: Financial Ratios 2008 to 2018",
       subtitle = "Enjoy",
       y = "Free Y Scale",
       x = "Date by Year") +
  theme_tq(base_size = 4, base_family = "")


```

### AAPL: Profitability Ratios

```{r}

AAPL2 %>%
  ggplot(aes(x = date, y = value)) +
  facet_wrap(~category + sub.section, ncol = 6, scales = "free" ) +
  geom_line() +
  labs(title = "AAPL: Profitability Ratios",
       y = "Free Y Scale",
       x = "Date by Year") +
  theme_tq(base_size = 4)

```

### AAPL: Growth Ratios

```{r}
AAPL3 %>%
  ggplot(aes(x = date, y = value)) +
  facet_wrap(~category + sub.section, ncol = 6, scales = "free" ) +
  geom_line() +
  labs(title = "AAPL: Growth Ratios",
       y = "Free Scale Y",
       x = "Date by Year") +
  theme_tq(base_size = 5)
```

### AAPL: Cash Flow Ratios

```{r}
AAPL4 %>%
  filter(sub.section == "Cash Flow Ratios") %>%
  ggplot(aes(x = date, y = value)) +
  facet_wrap(~category, nrow = 2, scales = "free") +
  geom_line() +
  labs(title = "AAPL: Cash Flow Ratios",
       subtile = "Data From Yahoo Finance",
       y = "Free Scale Y",
       x = "Date by Year") +
  theme_tq(base_size = 8)
```

### AAPL: Financial Health Ratios

```{r}
AAPL5 %>%
  ggplot(aes(x = date, y = value)) +
  facet_wrap(~category + sub.section, nrow = 5, scales = "free" ) +
  geom_line() +
  labs(title = "AAPL:Financial Health Ratios",
       y = "Free Y Scale",
       x = "Date by Year") +
  theme_tq(base_size = 4)
```

### AAPL: Efficiency Ratios

```{r}
AAPL6 %>%
  filter(sub.section == "Efficiency") %>%
  ggplot(aes(x = value, y = date)) +
  facet_wrap(~category, nrow = 4, scales = "free") +
  geom_line() +
  labs(title = "AAPL: Efficiency Ratios",
       subtile = "Enjoy",
       y = "Free Scale Y",
       x = "Date by Year") +
  theme_tq(base_size = 10)
```

### AAPL: Valuation Ratios

```{r}
AAPL7 %>%
  filter(sub.section == "Valuation Ratios") %>%
  ggplot(aes(x = date, y = value)) +
  facet_wrap(~category, nrow = 4, scales = "free") +
  geom_line() +
  labs(title = "AAPL: Valuation Ratios",
       subtile = "Enjoy",
       y = "Free Scale Y",
       x = "Date by Year") +
  theme_tq(base_size = 10)
```

### AAPL: Stock Price with MACD

```{r}
library(quantmod)
getSymbols("AAPL", src = "yahoo")
chartSeries(AAPL,
            subset = '2017-12::2018',
            show.grid = TRUE,
            time.scale = NULL,
            log.scale = FALSE,
            bar.type = "ohlc")
  addSMA(n = 50, on = 1, overlay = TRUE, col = "blue")
  addSMA(n = 20, on = 1, overlay = TRUE, col = "red")
  addMACD(fast = 12, slow = 26, signal = 9)
  addRSI(n = 14, maType = "EMA", wilder = TRUE)
```  

### AAPL: Candlestick + BBands + CCI

```{r}
chartSeries(AAPL, theme = 'white', subset = '2017-12::2018')
  addBBands()
  addCCI()
```

